package th.co.grouplease.vaadin10migration.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.MenuBar;

/**
 * Copyright (c) Group Lease Public Company Limited. All rights reserved. (http://www.grouplease.co.th/)
 * Author: Peeranut Ngaorungsri (peeranut.ng@grouplease.co.th) on 3/6/18 2:30 PM
 *
 */

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainMenuBarDesign extends CssLayout {
  protected Image logo;
  protected MenuBar applicationMenu;
  protected MenuBar contractMenu;
  protected MenuBar insuranceMenu;
  protected MenuBar profileLoggedInMenu;

  public MainMenuBarDesign() {
    Design.read(this);
  }
}
